// Seeds comprehensive Agrovet categories, suppliers, farmer customers, and 50 realistic products.
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();
const itemsOnly = process.argv.includes("--items-only");

const AGROVET_CATEGORIES = [
  { name: "Seeds & Planting Material", description: "Certified hybrid maize, vegetable seeds, and pasture grass" },
  { name: "Fertilizers & Soil Nutrition", description: "Planting DAP, top-dressing CAN/Urea, and foliar feeds" },
  { name: "Crop Protection (Agrochemicals)", description: "Herbicides, fungicides, insecticides, and grain protectants" },
  { name: "Veterinary Medicines & Vaccines", description: "Antibiotics, dewormers, acaricides, and vaccines (Cold Chain & POM)" },
  { name: "Animal Feeds & Mineral Nutrition", description: "Dairy meal, poultry feeds, mineral licks, and supplements" },
  { name: "Farm Tools & Veterinary Equipment", description: "Knapsack sprayers, drenching guns, syringes, and PPE" },
];

const SUPPLIERS = [
  { name: "Kenya Seed Company Ltd", contactPerson: "Joseph Tanui", email: "sales@kenyaseed.co.ke", phone: "0722204481", address: "Kitale, Kenya" },
  { name: "Twiga Chemical Industries Ltd", contactPerson: "Grace Mwangi", email: "info@twigachemicals.com", phone: "0733849200", address: "Old Airport North Rd, Nairobi" },
  { name: "Coopers Animal Health (K) Ltd", contactPerson: "Peter Kimani", email: "info@coopers.co.ke", phone: "0722204555", address: "Enterprise Rd, Nairobi" },
  { name: "Norbrook Africa Ltd", contactPerson: "Dr. James Otieno", email: "enquiries@norbrook.co.ke", phone: "0202403991", address: "Industrial Area, Nairobi" },
  { name: "Unga Farm Care (EA) Ltd", contactPerson: "David Kariuki", email: "customercare@unga.com", phone: "0711097000", address: "Commercial St, Nairobi" },
  { name: "Syngenta East Africa Ltd", contactPerson: "Mercy Wanjiku", email: "info.ke@syngenta.com", phone: "0203228000", address: "Valley Arcade, Nairobi" },
  { name: "Osho Chemical Industries Ltd", contactPerson: "Raju Patel", email: "oshochem@oshochemicals.com", phone: "0711045000", address: "Sasio Rd, Off Lunga Lunga Rd, Nairobi" },
  { name: "Yara East Africa Ltd", contactPerson: "Brian Koech", email: "info.kenya@yara.com", phone: "0202408000", address: "Westlands, Nairobi" },
];

const FARMERS = [
  { name: "John Kiprono Chepkwony", phone: "0712345678", email: "kiprono@eldoretfarms.com", address: "Moiben, Uasin Gishu", customerType: "registered", canBuyOnCredit: true, creditLimit: 50000, currentCreditBalance: 8500 },
  { name: "Mary Wambui Karanja", phone: "0723456789", email: "mary.karanja@gmail.com", address: "Kinangop, Nyandarua", customerType: "registered", canBuyOnCredit: true, creditLimit: 35000, currentCreditBalance: 0 },
  { name: "Peter Mwangi Kimani", phone: "0734567890", email: "mwangi.poultry@yahoo.com", address: "Gatundu, Kiambu", customerType: "registered", canBuyOnCredit: true, creditLimit: 40000, currentCreditBalance: 12000 },
  { name: "Fatuma Hassan Abdi", phone: "0798765432", email: "fatuma.livestock@gmail.com", address: "Garissa / Isiolo border", customerType: "walk_in", canBuyOnCredit: false, creditLimit: 0, currentCreditBalance: 0 },
  { name: "David Ochieng Otieno", phone: "0787654321", email: "ochieng.ahero@gmail.com", address: "Ahero Rice Scheme, Kisumu", customerType: "registered", canBuyOnCredit: true, creditLimit: 25000, currentCreditBalance: 3200 },
];

const PRODUCTS = [
  // ─────────────────────────── Seeds & Planting Material ───────────────────────────
  {
    category: "Seeds & Planting Material",
    sku: "SEED-MZ-H614-2KG",
    name: "H614D Hybrid Maize 2kg",
    genericName: "Hybrid Maize H614D (Highland)",
    brandName: "Kenya Seed",
    packSize: "2kg",
    manufacturer: "Kenya Seed Company",
    prescriptionRequired: false,
    costPrice: 500,
    sellingPrice: 620,
    quantity: 80,
    reorderLevel: 15,
    monthsExpiry: 18,
    description: "Top-yielding certified highland hybrid maize seed for altitudes between 1500m - 2100m. Maturity: 5-6 months.",
  },
  {
    category: "Seeds & Planting Material",
    sku: "SEED-MZ-H6213-2KG",
    name: "H6213 Highland Maize 2kg",
    genericName: "Hybrid Maize H6213",
    brandName: "Kenya Seed",
    packSize: "2kg",
    manufacturer: "Kenya Seed Company",
    prescriptionRequired: false,
    costPrice: 520,
    sellingPrice: 640,
    quantity: 60,
    reorderLevel: 12,
    monthsExpiry: 18,
    description: "High altitude hybrid with strong resistance to Grey Leaf Spot and Maize Streak Virus. Excellent flour recovery.",
  },
  {
    category: "Seeds & Planting Material",
    sku: "SEED-MZ-DUMA43-2KG",
    name: "SC Duma 43 Maize 2kg",
    genericName: "Early Maturing Maize SC Duma 43",
    brandName: "Seed Co",
    packSize: "2kg",
    manufacturer: "Seed Co Kenya",
    prescriptionRequired: false,
    costPrice: 530,
    sellingPrice: 650,
    quantity: 50,
    reorderLevel: 10,
    monthsExpiry: 18,
    description: "Fast maturing drought-tolerant hybrid. Reaches harvest in 90-110 days. Ideal for medium-dry ecological zones.",
  },
  {
    category: "Seeds & Planting Material",
    sku: "SEED-MZ-DK8031-2KG",
    name: "DK 8031 Dekalb Maize 2kg",
    genericName: "Hybrid White Maize DK8031",
    brandName: "Bayer Dekalb",
    packSize: "2kg",
    manufacturer: "Bayer CropScience",
    prescriptionRequired: false,
    costPrice: 560,
    sellingPrice: 680,
    quantity: 45,
    reorderLevel: 10,
    monthsExpiry: 18,
    description: "High yielding double-cobbing hybrid with excellent standability and high test weight grain.",
  },
  {
    category: "Seeds & Planting Material",
    sku: "SEED-MZ-H614-10KG",
    name: "H614D Hybrid Maize 10kg",
    genericName: "Hybrid Maize H614D (Highland)",
    brandName: "Kenya Seed",
    packSize: "10kg",
    manufacturer: "Kenya Seed Company",
    prescriptionRequired: false,
    costPrice: 2400,
    sellingPrice: 2900,
    quantity: 30,
    reorderLevel: 5,
    monthsExpiry: 18,
    description: "10kg bulk bag planting 1 acre. Certified treated with apron star against early soil-borne pests.",
  },
  {
    category: "Seeds & Planting Material",
    sku: "SEED-VEG-SUK-100G",
    name: "Sukuma Wiki (Collards) 100g",
    genericName: "Brassica oleracea acephala",
    brandName: "Simlaw Seeds",
    packSize: "100g",
    manufacturer: "Simlaw Seeds Kenya",
    prescriptionRequired: false,
    costPrice: 220,
    sellingPrice: 320,
    quantity: 70,
    reorderLevel: 15,
    monthsExpiry: 24,
    description: "Thousand headed vigorous collards. High leaf regeneration rate, continuous picking for up to 9 months.",
  },
  {
    category: "Seeds & Planting Material",
    sku: "SEED-VEG-GLORIA-50G",
    name: "Gloria F1 Cabbage Seeds 50g",
    genericName: "Cabbage Hybrid Gloria F1",
    brandName: "Seminis",
    packSize: "50g",
    manufacturer: "Bayer / Seminis",
    prescriptionRequired: false,
    costPrice: 2800,
    sellingPrice: 3400,
    quantity: 25,
    reorderLevel: 5,
    monthsExpiry: 24,
    description: "Market-leading compact round cabbage. Excellent field holding ability (stays in field 3+ weeks without splitting).",
  },
  {
    category: "Seeds & Planting Material",
    sku: "SEED-VEG-KILELE-10G",
    name: "Kilele F1 Determinate Tomato 10g",
    genericName: "Tomato F1 Hybrid",
    brandName: "Syngenta",
    packSize: "10g",
    manufacturer: "Syngenta",
    prescriptionRequired: false,
    costPrice: 2100,
    sellingPrice: 2600,
    quantity: 20,
    reorderLevel: 5,
    monthsExpiry: 24,
    description: "Determinate hybrid tomato with strong resistance to Bacterial Wilt and TYLCV. Oval firm fruits, long shelf life.",
  },
  {
    category: "Seeds & Planting Material",
    sku: "SEED-PAS-RHODES-1KG",
    name: "Boma Rhodes Pasture Seed 1kg",
    genericName: "Chloris gayana (Rhodes Grass)",
    brandName: "Kenya Seed",
    packSize: "1kg",
    manufacturer: "Kenya Seed Company",
    prescriptionRequired: false,
    costPrice: 850,
    sellingPrice: 1100,
    quantity: 40,
    reorderLevel: 8,
    monthsExpiry: 24,
    description: "Nutritious high-biomass dairy pasture grass. Excellent for baling hay and rotational grazing.",
  },

  // ─────────────────────────── Fertilizers & Soil Nutrition ───────────────────────────
  {
    category: "Fertilizers & Soil Nutrition",
    sku: "FERT-DAP-50KG",
    name: "DAP Planting Fertilizer 50kg",
    genericName: "Diammonium Phosphate 18-46-0",
    brandName: "Yara",
    packSize: "50kg bag",
    manufacturer: "Yara East Africa",
    prescriptionRequired: false,
    costPrice: 3600,
    sellingPrice: 4200,
    quantity: 120,
    reorderLevel: 25,
    monthsExpiry: null,
    description: "Essential basal planting fertilizer. Provides 18% Nitrogen and 46% Phosphate for robust seedling root development.",
  },
  {
    category: "Fertilizers & Soil Nutrition",
    sku: "FERT-CAN-50KG",
    name: "CAN Top Dressing Fertilizer 50kg",
    genericName: "Calcium Ammonium Nitrate 26% N",
    brandName: "Yara",
    packSize: "50kg bag",
    manufacturer: "Yara East Africa",
    prescriptionRequired: false,
    costPrice: 2800,
    sellingPrice: 3400,
    quantity: 100,
    reorderLevel: 20,
    monthsExpiry: null,
    description: "Top-dressing nitrogen fertilizer (26% N) with Calcium. Does not acidify soil; rapidly absorbed by growing crops.",
  },
  {
    category: "Fertilizers & Soil Nutrition",
    sku: "FERT-NPK-17-50KG",
    name: "NPK 17-17-17 Fertilizer 50kg",
    genericName: "Compound Fertilizer 17-17-17",
    brandName: "YaraMila",
    packSize: "50kg bag",
    manufacturer: "Yara East Africa",
    prescriptionRequired: false,
    costPrice: 3800,
    sellingPrice: 4500,
    quantity: 60,
    reorderLevel: 10,
    monthsExpiry: null,
    description: "Balanced multi-nutrient compound for horticultural crops, potatoes, coffee, tea, and fruit trees.",
  },
  {
    category: "Fertilizers & Soil Nutrition",
    sku: "FERT-DAP-10KG",
    name: "DAP Planting Fertilizer 10kg",
    genericName: "Diammonium Phosphate 18-46-0",
    brandName: "Yara",
    packSize: "10kg bag",
    manufacturer: "Yara East Africa",
    prescriptionRequired: false,
    costPrice: 760,
    sellingPrice: 950,
    quantity: 50,
    reorderLevel: 10,
    monthsExpiry: null,
    description: "Repackaged convenient 10kg bag for kitchen gardens and smallholder plots.",
  },
  {
    category: "Fertilizers & Soil Nutrition",
    sku: "FERT-CAN-10KG",
    name: "CAN Top Dressing Fertilizer 10kg",
    genericName: "Calcium Ammonium Nitrate 26% N",
    brandName: "Yara",
    packSize: "10kg bag",
    manufacturer: "Yara East Africa",
    prescriptionRequired: false,
    costPrice: 600,
    sellingPrice: 780,
    quantity: 45,
    reorderLevel: 10,
    monthsExpiry: null,
    description: "Repackaged 10kg top-dressing bag for smallholder farmers.",
  },
  {
    category: "Fertilizers & Soil Nutrition",
    sku: "FERT-FOL-EASY-VEG-1KG",
    name: "Easygro Vegetative Foliar 1kg",
    genericName: "Water-soluble NPK 27-10-10 + Micro-nutrients",
    brandName: "Twiga Chemical",
    packSize: "1kg",
    manufacturer: "Twiga Chemical Industries",
    prescriptionRequired: false,
    costPrice: 650,
    sellingPrice: 850,
    quantity: 40,
    reorderLevel: 8,
    monthsExpiry: 36,
    description: "High nitrogen foliar feed with chelated trace elements (Zn, Fe, Cu, Mn, B). Promotes vigorous leaf and shoot growth. Rate: 30-40g / 20L knapsack.",
  },
  {
    category: "Fertilizers & Soil Nutrition",
    sku: "FERT-FOL-EASY-FLOWER-1KG",
    name: "Easygro Flower & Fruit Foliar 1kg",
    genericName: "Water-soluble NPK 14-10-34 + Micro-nutrients",
    brandName: "Twiga Chemical",
    packSize: "1kg",
    manufacturer: "Twiga Chemical Industries",
    prescriptionRequired: false,
    costPrice: 680,
    sellingPrice: 890,
    quantity: 35,
    reorderLevel: 8,
    monthsExpiry: 36,
    description: "High potassium foliar feed. Prevents flower and fruit drop, boosts fruit size, sweetness, and grain filling. Rate: 40g / 20L knapsack.",
  },

  // ─────────────────────────── Crop Protection (Agrochemicals) ───────────────────────────
  {
    category: "Crop Protection (Agrochemicals)",
    sku: "CHEM-HERB-ROUNDUP-1L",
    name: "Roundup Turbo Glyphosate 1L",
    genericName: "Glyphosate 450g/L (Systemic Herbicide)",
    brandName: "Bayer",
    packSize: "1L",
    manufacturer: "Bayer CropScience",
    prescriptionRequired: false,
    costPrice: 1200,
    sellingPrice: 1550,
    quantity: 60,
    reorderLevel: 15,
    monthsExpiry: 24,
    description: "Transorb technology non-selective systemic herbicide. Kills annual and perennial grasses and broadleaves down to the root. Mixing: 150ml - 200ml per 20L knapsack.",
  },
  {
    category: "Crop Protection (Agrochemicals)",
    sku: "CHEM-HERB-WEEDAL-1L",
    name: "Weedal 480 SL Herbicide 1L",
    genericName: "Glyphosate 480g/L",
    brandName: "Twiga Chemical",
    packSize: "1L",
    manufacturer: "Twiga Chemical Industries",
    prescriptionRequired: false,
    costPrice: 850,
    sellingPrice: 1100,
    quantity: 50,
    reorderLevel: 10,
    monthsExpiry: 24,
    description: "Affordable systemic non-selective herbicide for land clearing and minimum tillage. Mixing: 200ml per 20L knapsack.",
  },
  {
    category: "Crop Protection (Agrochemicals)",
    sku: "CHEM-HERB-24D-1L",
    name: "2,4-D Amine 720 SL Selective 1L",
    genericName: "2,4-D Dimethylamine salt 720g/L",
    brandName: "Osho Chemical",
    packSize: "1L",
    manufacturer: "Osho Chemical Industries",
    prescriptionRequired: false,
    costPrice: 750,
    sellingPrice: 980,
    quantity: 45,
    reorderLevel: 10,
    monthsExpiry: 24,
    description: "Post-emergence selective herbicide for control of annual and perennial broadleaf weeds in maize, wheat, barley, and sugarcane. Safe on graminaceous crops.",
  },
  {
    category: "Crop Protection (Agrochemicals)",
    sku: "CHEM-FUNG-RIDOMIL-1KG",
    name: "Ridomil Gold MZ 68 WG 1kg",
    genericName: "Metalaxyl-M 40g/kg + Mancozeb 640g/kg",
    brandName: "Syngenta",
    packSize: "1kg",
    manufacturer: "Syngenta",
    prescriptionRequired: false,
    costPrice: 2600,
    sellingPrice: 3150,
    quantity: 30,
    reorderLevel: 6,
    monthsExpiry: 24,
    description: "Premium systemic & contact fungicide for control of Late Blight in potatoes & tomatoes, and Downy Mildew in onions. Pre-harvest interval (PHI): 7 days.",
  },
  {
    category: "Crop Protection (Agrochemicals)",
    sku: "CHEM-FUNG-OSHOTHANE-1KG",
    name: "Oshothane 80 WP Fungicide 1kg",
    genericName: "Mancozeb 800g/kg",
    brandName: "Osho Chemical",
    packSize: "1kg",
    manufacturer: "Osho Chemical Industries",
    prescriptionRequired: false,
    costPrice: 750,
    sellingPrice: 950,
    quantity: 50,
    reorderLevel: 12,
    monthsExpiry: 24,
    description: "Broad-spectrum protective contact fungicide. Prevents early and late blight, leaf spots, and rusts. Rate: 50g per 20L sprayer.",
  },
  {
    category: "Crop Protection (Agrochemicals)",
    sku: "CHEM-INSECT-DUDUTHRIN-1L",
    name: "Duduthrin 1.75 EC Insecticide 1L",
    genericName: "Lambda-cyhalothrin 17.5g/L",
    brandName: "Twiga Chemical",
    packSize: "1L",
    manufacturer: "Twiga Chemical Industries",
    prescriptionRequired: false,
    costPrice: 1300,
    sellingPrice: 1700,
    quantity: 35,
    reorderLevel: 8,
    monthsExpiry: 24,
    description: "Rapid knockdown contact and stomach pyrethroid insecticide. Controls caterpillars, aphids, thrips, and beetles on vegetables and cereals. Rate: 20-30ml per 20L knapsack.",
  },
  {
    category: "Crop Protection (Agrochemicals)",
    sku: "CHEM-INSECT-THUNDER-250ML",
    name: "Thunder 145 OD Insecticide 250ml",
    genericName: "Imidacloprid 100g/L + Beta-cyfluthrin 45g/L",
    brandName: "Bayer",
    packSize: "250ml",
    manufacturer: "Bayer CropScience",
    prescriptionRequired: false,
    costPrice: 1100,
    sellingPrice: 1450,
    quantity: 40,
    reorderLevel: 8,
    monthsExpiry: 24,
    description: "Dual active systemic and contact insecticide. Outstanding efficacy against whiteflies, aphids, thrips, and Tuta absoluta in tomatoes. PHI: 3 days.",
  },
  {
    category: "Crop Protection (Agrochemicals)",
    sku: "CHEM-POST-ACTELLIC-50G",
    name: "Actellic Super Dust 50g",
    genericName: "Pirimiphos-methyl 16g/kg + Permethrin 3g/kg",
    brandName: "Syngenta",
    packSize: "50g sachet",
    manufacturer: "Syngenta",
    prescriptionRequired: false,
    costPrice: 75,
    sellingPrice: 110,
    quantity: 160,
    reorderLevel: 30,
    monthsExpiry: 24,
    description: "Post-harvest grain protectant dust. Protects stored maize, beans, and sorghum against Larger Grain Borer (LGB) and weevils for up to 9 months. 50g treats two 90kg bags.",
  },
  {
    category: "Crop Protection (Agrochemicals)",
    sku: "CHEM-POST-ACTELLIC-100G",
    name: "Actellic Super Dust 100g",
    genericName: "Pirimiphos-methyl 16g/kg + Permethrin 3g/kg",
    brandName: "Syngenta",
    packSize: "100g sachet",
    manufacturer: "Syngenta",
    prescriptionRequired: false,
    costPrice: 140,
    sellingPrice: 200,
    quantity: 110,
    reorderLevel: 25,
    monthsExpiry: 24,
    description: "100g sachet treating four 90kg bags of dry shelled maize.",
  },

  // ─────────────────────────── Veterinary Medicines & Vaccines ───────────────────────────
  {
    category: "Veterinary Medicines & Vaccines",
    sku: "VET-AB-ALA20-100ML",
    name: "Alamycin LA 20% 100ml",
    genericName: "Oxytetracycline 200mg/ml (20% LA)",
    brandName: "Norbrook",
    strength: "200mg/ml",
    dosageForm: "injection",
    packSize: "100ml vial",
    manufacturer: "Norbrook Laboratories",
    prescriptionRequired: true,
    costPrice: 750,
    sellingPrice: 1000,
    quantity: 45,
    reorderLevel: 10,
    monthsExpiry: 24,
    description: "POM - Long-acting broad spectrum antibiotic for cattle, sheep, and pigs. Indicated for respiratory diseases, Anaplasmosis, Heartwater, and Foot rot. Dose: 1ml / 10kg body weight IM. WITHDRAWAL: Meat: 21 days, Milk: 7 days.",
  },
  {
    category: "Veterinary Medicines & Vaccines",
    sku: "VET-AB-PENSTRIP-100ML",
    name: "Pen & Strep Injection 100ml",
    genericName: "Procaine Penicillin 200mg + Dihydrostreptomycin 250mg",
    brandName: "Norbrook",
    strength: "20/25",
    dosageForm: "injection",
    packSize: "100ml vial",
    manufacturer: "Norbrook Laboratories",
    prescriptionRequired: true,
    costPrice: 850,
    sellingPrice: 1150,
    quantity: 35,
    reorderLevel: 8,
    monthsExpiry: 24,
    description: "POM - Injectable bactericidal antibiotic combination against Gram-positive and Gram-negative infections, metritis, and wound sepsis. WITHDRAWAL: Meat: 30 days, Milk: 5 days.",
  },
  {
    category: "Veterinary Medicines & Vaccines",
    sku: "VET-DEW-WORM-1L",
    name: "Wormicid 10% Dewormer 1L",
    genericName: "Albendazole 100mg/ml (10% Drench)",
    brandName: "Twiga Chemical",
    strength: "10%",
    dosageForm: "suspension",
    packSize: "1L",
    manufacturer: "Twiga Chemical Industries",
    prescriptionRequired: false,
    costPrice: 900,
    sellingPrice: 1200,
    quantity: 40,
    reorderLevel: 10,
    monthsExpiry: 24,
    description: "Broad-spectrum oral anthelmintic drench for cattle, sheep, goats against roundworms, lungworms, tapeworms, and adult liver flukes. Dose: 7.5ml - 10ml / 100kg body weight. WITHDRAWAL: Meat: 14 days, Milk: 3 days.",
  },
  {
    category: "Veterinary Medicines & Vaccines",
    sku: "VET-DEW-WORM-120ML",
    name: "Wormicid 2.5% Dewormer 120ml",
    genericName: "Albendazole 25mg/ml (2.5% Drench)",
    brandName: "Twiga Chemical",
    strength: "2.5%",
    dosageForm: "suspension",
    packSize: "120ml",
    manufacturer: "Twiga Chemical Industries",
    prescriptionRequired: false,
    costPrice: 120,
    sellingPrice: 180,
    quantity: 75,
    reorderLevel: 15,
    monthsExpiry: 24,
    description: "Oral drench for calves, sheep, and goats. Safe for young stock.",
  },
  {
    category: "Veterinary Medicines & Vaccines",
    sku: "VET-DEW-NILZAN-1L",
    name: "Nilzan Plus Drench 1L",
    genericName: "Levamisole HCl 3.0% + Oxyclozanide 6.0% + Cobalt",
    brandName: "Coopers",
    strength: "Levamisole + Oxyclozanide",
    dosageForm: "suspension",
    packSize: "1L",
    manufacturer: "Coopers Animal Health",
    prescriptionRequired: false,
    costPrice: 1850,
    sellingPrice: 2350,
    quantity: 28,
    reorderLevel: 6,
    monthsExpiry: 24,
    description: "Combined flukicide and wormer with cobalt supplement. Eradicates stomach worms and liver fluke. WITHDRAWAL: Meat: 28 days, Milk: 3 days.",
  },
  {
    category: "Veterinary Medicines & Vaccines",
    sku: "VET-INJ-IVOMEC-50ML",
    name: "Ivomec Super Injection 50ml",
    genericName: "Ivermectin 10mg/ml + Clorsulon 100mg/ml",
    brandName: "Boehringer",
    strength: "1% + 10%",
    dosageForm: "injection",
    packSize: "50ml",
    manufacturer: "Boehringer Ingelheim",
    prescriptionRequired: true,
    costPrice: 1650,
    sellingPrice: 2150,
    quantity: 22,
    reorderLevel: 5,
    monthsExpiry: 24,
    description: "POM - Subcutaneous injection for cattle. Controls internal parasites (gastrointestinal worms, lungworms, adult liver fluke) and external parasites (sucking lice, mange mites). Meat withdrawal: 66 days. Do NOT use in lactating dairy cows.",
  },
  {
    category: "Veterinary Medicines & Vaccines",
    sku: "VET-DIP-TRIATIX-1L",
    name: "Triatix Cattle Dip / Spray 1L",
    genericName: "Amitraz 12.5% EC (Acaricide)",
    brandName: "Coopers",
    strength: "12.5% EC",
    dosageForm: "other",
    packSize: "1L",
    manufacturer: "Coopers Animal Health",
    prescriptionRequired: false,
    costPrice: 2100,
    sellingPrice: 2650,
    quantity: 35,
    reorderLevel: 8,
    monthsExpiry: 24,
    description: "Premier acaricide for plunge dips and spray races. Controls all stages of ticks (including resistant blue ticks), mange mites, and lice on cattle and pigs. Dilution: 1L per 500L water. Zero milk withdrawal.",
  },
  {
    category: "Veterinary Medicines & Vaccines",
    sku: "VET-DIP-DECATIX-1L",
    name: "Decatix Pour-On Dip 1L",
    genericName: "Deltamethrin 10g/L",
    brandName: "Coopers",
    strength: "1% pour-on",
    dosageForm: "other",
    packSize: "1L",
    manufacturer: "Coopers Animal Health",
    prescriptionRequired: false,
    costPrice: 2400,
    sellingPrice: 3050,
    quantity: 25,
    reorderLevel: 5,
    monthsExpiry: 24,
    description: "Ready-to-use pour-on. Applied along backline from poll to base of tail. Controls ticks, tsetse flies, biting flies, and nuisance flies for up to 4 weeks.",
  },
  {
    category: "Veterinary Medicines & Vaccines",
    sku: "VET-MAST-MASTRITE-BOX",
    name: "Mastrite Intramammary (Box 20)",
    genericName: "Cloxacillin Sodium 200mg + Ampicillin 75mg",
    brandName: "Norbrook",
    strength: "275mg/tube",
    dosageForm: "other",
    packSize: "Box of 20 tubes",
    manufacturer: "Norbrook Laboratories",
    prescriptionRequired: true,
    costPrice: 1250,
    sellingPrice: 1650,
    quantity: 26,
    reorderLevel: 5,
    monthsExpiry: 24,
    description: "POM - Lactating cow intra-mammary infusion for clinical mastitis. Infuse one tube into infected quarter every 12 hours after milking. Milk withdrawal: 72 hours (6 milkings).",
  },
  {
    category: "Veterinary Medicines & Vaccines",
    sku: "VET-POULT-ALISERYL-100G",
    name: "Aliseryl WS Powder 100g",
    genericName: "Erythromycin + Oxytetracycline + Streptomycin + Colistin + 10 Vitamins",
    brandName: "Interchemie",
    strength: "Compound",
    dosageForm: "sachet",
    packSize: "100g sachet",
    manufacturer: "Interchemie Holland",
    prescriptionRequired: false,
    costPrice: 360,
    sellingPrice: 520,
    quantity: 70,
    reorderLevel: 15,
    monthsExpiry: 24,
    description: "Water soluble antibiotic-vitamin blend for poultry. Treats Chronic Respiratory Disease (CRD), Fowl Cholera, infectious coryza, and general stress.",
  },
  {
    category: "Veterinary Medicines & Vaccines",
    sku: "VET-VAC-LASOTA-1000",
    name: "Newcastle Disease LaSota Vaccine",
    genericName: "Newcastle Disease Virus (LaSota strain)",
    brandName: "KEVEVAPI",
    strength: "1000 Doses",
    dosageForm: "injection",
    packSize: "1 vial (1000 doses)",
    manufacturer: "KEVEVAPI",
    prescriptionRequired: true,
    costPrice: 300,
    sellingPrice: 450,
    quantity: 45,
    reorderLevel: 10,
    monthsExpiry: 8,
    description: "POM - COLD CHAIN CRITICAL (Must be stored at 2°C - 8°C). Live attenuated vaccine administered via drinking water or eye-drop for active immunization of poultry.",
  },

  // ─────────────────────────── Animal Feeds & Mineral Nutrition ───────────────────────────
  {
    category: "Animal Feeds & Mineral Nutrition",
    sku: "FEED-DRY-FUGO-50KG",
    name: "Unga Fugo Standard Dairy 50kg",
    genericName: "Dairy Meal 16% Crude Protein",
    brandName: "Unga Farm Care",
    packSize: "50kg bag",
    manufacturer: "Unga Farm Care (EA)",
    prescriptionRequired: false,
    costPrice: 2150,
    sellingPrice: 2500,
    quantity: 90,
    reorderLevel: 20,
    monthsExpiry: 6,
    description: "High energy, high protein balanced dairy meal for lactating cows. Formulated with balanced calcium and phosphorus to maximize milk yield and butterfat.",
  },
  {
    category: "Animal Feeds & Mineral Nutrition",
    sku: "FEED-POULT-CHICK-50KG",
    name: "Unga Fugo Chick Mash 50kg",
    genericName: "Chick Starter Mash 18% Crude Protein",
    brandName: "Unga Farm Care",
    packSize: "50kg bag",
    manufacturer: "Unga Farm Care (EA)",
    prescriptionRequired: false,
    costPrice: 2650,
    sellingPrice: 3100,
    quantity: 45,
    reorderLevel: 10,
    monthsExpiry: 6,
    description: "Complete starter feed for egg-strain chicks from day 1 to 8 weeks. Fortified with essential amino acids and coccidiostat.",
  },
  {
    category: "Animal Feeds & Mineral Nutrition",
    sku: "FEED-POULT-LAYERS-50KG",
    name: "Unga Fugo Layers Mash 50kg",
    genericName: "Layers Mash 16% CP + 4% Calcium",
    brandName: "Unga Farm Care",
    packSize: "50kg bag",
    manufacturer: "Unga Farm Care (EA)",
    prescriptionRequired: false,
    costPrice: 2450,
    sellingPrice: 2850,
    quantity: 65,
    reorderLevel: 15,
    monthsExpiry: 6,
    description: "Complete diet for laying birds from 18 weeks onwards. High available calcium and phosphorus for strong eggshells and prolonged peak production.",
  },
  {
    category: "Animal Feeds & Mineral Nutrition",
    sku: "FEED-MIN-MACLIK-SUP-10KG",
    name: "Maclik Super Mineral Lick 10kg",
    genericName: "High Phosphorus Cattle Mineral (P: 10%, Ca: 15%)",
    brandName: "Coopers",
    packSize: "10kg block",
    manufacturer: "Coopers Animal Health",
    prescriptionRequired: false,
    costPrice: 1150,
    sellingPrice: 1450,
    quantity: 55,
    reorderLevel: 12,
    monthsExpiry: 36,
    description: "Weather-resistant mineral brick for lactating dairy cows. Improves fertility, reduces calving intervals, and prevents milk fever.",
  },
  {
    category: "Animal Feeds & Mineral Nutrition",
    sku: "FEED-MIN-MACLIK-DRY-10KG",
    name: "Maclik Dry Cow Mineral 10kg",
    genericName: "Low Calcium Transition Mineral Block",
    brandName: "Coopers",
    packSize: "10kg block",
    manufacturer: "Coopers Animal Health",
    prescriptionRequired: false,
    costPrice: 1200,
    sellingPrice: 1500,
    quantity: 35,
    reorderLevel: 8,
    monthsExpiry: 36,
    description: "Specialized formula for in-calf cows during the last 60 days of pregnancy (steaming period). Prevents hypocalcaemia (milk fever) at calving.",
  },
  {
    category: "Animal Feeds & Mineral Nutrition",
    sku: "FEED-MIN-ROCK-SALT-5KG",
    name: "Natural Rock Salt Mineral 5kg",
    genericName: "Pure Natural Halite Mineral Block",
    brandName: "Generic Agro",
    packSize: "5kg block",
    manufacturer: "Kenya Salt Suppliers",
    prescriptionRequired: false,
    costPrice: 260,
    sellingPrice: 380,
    quantity: 80,
    reorderLevel: 15,
    monthsExpiry: null,
    description: "Natural hard rock salt block with hanging rope. Provides essential sodium and trace electrolytes for cattle, goats, and horses.",
  },
  {
    category: "Animal Feeds & Mineral Nutrition",
    sku: "FEED-SUP-VITALYTE-100G",
    name: "Vitalyte Vitamin + Electrolyte 100g",
    genericName: "Vitamins A, D3, E, B-Complex + Mineral Electrolytes",
    brandName: "Twiga Chemical",
    packSize: "100g sachet",
    manufacturer: "Twiga Chemical Industries",
    prescriptionRequired: false,
    costPrice: 180,
    sellingPrice: 260,
    quantity: 90,
    reorderLevel: 20,
    monthsExpiry: 24,
    description: "Soluble multivitamin and electrolyte powder for poultry and livestock during vaccination, transport stress, disease recovery, or extreme heat.",
  },
  {
    category: "Animal Feeds & Mineral Nutrition",
    sku: "FEED-SUP-MILK-SALVE-500G",
    name: "Mastrite Teat Salve 500g",
    genericName: "Antiseptic Milking Jelly (Chlorhexidine)",
    brandName: "Norbrook",
    packSize: "500g tub",
    manufacturer: "Norbrook Laboratories",
    prescriptionRequired: false,
    costPrice: 320,
    sellingPrice: 450,
    quantity: 45,
    reorderLevel: 10,
    monthsExpiry: 36,
    description: "Smooth antiseptic milking lubricant. Heals chapped teats, prevents teat sores, and inhibits bacteria entry into the teat canal during milking.",
  },

  // ─────────────────────────── Farm Tools & Veterinary Equipment ───────────────────────────
  {
    category: "Farm Tools & Veterinary Equipment",
    sku: "TOOL-SP-CP3-16L",
    name: "CP3 Classic Knapsack 16L",
    genericName: "Heavy-Duty Compression Sprayer 16L",
    brandName: "Cooper Pegler",
    packSize: "1 complete unit",
    manufacturer: "Cooper Pegler",
    prescriptionRequired: false,
    costPrice: 4800,
    sellingPrice: 5950,
    quantity: 16,
    reorderLevel: 3,
    monthsExpiry: null,
    description: "The gold standard diaphragm pump knapsack sprayer. Ergonomic UV-stabilized tank, brass trigger lance, pressure relief valve, unbreakable durability.",
  },
  {
    category: "Farm Tools & Veterinary Equipment",
    sku: "TOOL-SP-FARMATE-16L",
    name: "Farmate Knapsack Sprayer 16L",
    genericName: "Manual Lever Knapsack Sprayer 16L",
    brandName: "Farmate",
    packSize: "1 complete unit",
    manufacturer: "Farmate International",
    prescriptionRequired: false,
    costPrice: 2900,
    sellingPrice: 3700,
    quantity: 22,
    reorderLevel: 4,
    monthsExpiry: null,
    description: "Durable and affordable 16L knapsack sprayer. Comes with stainless steel lance and set of 3 interchangeable spray nozzles.",
  },
  {
    category: "Farm Tools & Veterinary Equipment",
    sku: "TOOL-VET-DRENCH-GUN-30ML",
    name: "Automatic Drenching Gun 30ml",
    genericName: "Adjustable Automatic Oral Doser 30ml",
    brandName: "Simcro",
    packSize: "1 unit + feed tube",
    manufacturer: "Simcro Products",
    prescriptionRequired: false,
    costPrice: 1850,
    sellingPrice: 2450,
    quantity: 14,
    reorderLevel: 3,
    monthsExpiry: null,
    description: "Heavy-duty ergonomic automatic drenching gun with calibrated dose selector (5ml - 30ml) for rapid cattle and sheep worming.",
  },
  {
    category: "Farm Tools & Veterinary Equipment",
    sku: "TOOL-VET-SYRINGE-20ML",
    name: "Reusable Vet Syringe 20ml",
    genericName: "Metal/Glass Autoclavable Syringe 20ml",
    brandName: "Kerbl",
    packSize: "1 unit",
    manufacturer: "Kerbl Veterinary",
    prescriptionRequired: false,
    costPrice: 480,
    sellingPrice: 680,
    quantity: 28,
    reorderLevel: 5,
    monthsExpiry: null,
    description: "Durable chrome-plated metal syringe with tempered glass barrel and luer-lock tip. Fully boilable and reusable for livestock vaccination.",
  },
  {
    category: "Farm Tools & Veterinary Equipment",
    sku: "TOOL-VET-NEEDLES-16G-100",
    name: "Vet Hypodermic Needles 16G (Box 100)",
    genericName: "Stainless Steel Luer-Lock Needles 16G x 1\"",
    brandName: "Ideal",
    packSize: "Box of 100",
    manufacturer: "Ideal Instruments",
    prescriptionRequired: false,
    costPrice: 380,
    sellingPrice: 580,
    quantity: 35,
    reorderLevel: 8,
    monthsExpiry: null,
    description: "Heavy gauge 16G x 1 inch aluminium hub needles suitable for thick antibiotic suspension injections in cattle.",
  },
  {
    category: "Farm Tools & Veterinary Equipment",
    sku: "TOOL-PPE-GLOVES-NITRILE",
    name: "Chemical Resistant Gloves (Pair)",
    genericName: "Nitrile Safety Chemical Handling Gloves",
    brandName: "Delta Plus",
    packSize: "1 pair",
    manufacturer: "Delta Plus",
    prescriptionRequired: false,
    costPrice: 160,
    sellingPrice: 260,
    quantity: 55,
    reorderLevel: 15,
    monthsExpiry: null,
    description: "Flock-lined green nitrile gloves for safe handling and spraying of herbicides, insecticides, and tick dips.",
  },
];

async function main() {
  console.log("🌱 Starting Agrovet Database Seeding...\n");

  // 1. Seed Agrovet Categories
  console.log("1. Seeding Agrovet Categories...");
  const categoryMap = {};
  for (const cat of AGROVET_CATEGORIES) {
    const c = await prisma.category.upsert({
      where: { name: cat.name },
      update: itemsOnly ? {} : { description: cat.description },
      create: { name: cat.name, description: cat.description },
    });
    categoryMap[cat.name] = c.id;
    console.log(`   ✓ Category: ${c.name}`);
  }

  // 2. Ensure Main Branch exists
  let branch = await prisma.branch.findFirst({ where: { isMain: true } });
  if (!branch) {
    branch = await prisma.branch.findFirst();
  }
  if (!branch) {
    branch = await prisma.branch.create({
      data: { name: "Main Agrovet Store", code: "MAIN", isMain: true, isActive: true, stockDistributionPercentage: 100 },
    });
  }
  console.log(`\n2. Target Branch: ${branch.name} (${branch.code})`);

  // 3. Seed Suppliers
  console.log("\n3. Seeding Agrovet Suppliers...");
  for (const sup of itemsOnly ? [] : SUPPLIERS) {
    const s = await prisma.supplier.upsert({
      where: { id: (await prisma.supplier.findFirst({ where: { name: sup.name } }))?.id || "000000000000000000000000" },
      update: sup,
      create: sup,
    });
    console.log(`   ✓ Supplier: ${s.name}`);
  }

  // 4. Seed Farmer Customers (with credit limits)
  console.log("\n4. Seeding Farmer Customers...");
  for (const farmer of itemsOnly ? [] : FARMERS) {
    const f = await prisma.customer.upsert({
      where: { phone: farmer.phone },
      update: farmer,
      create: farmer,
    });
    console.log(`   ✓ Farmer: ${f.name} (Credit Limit: KSh ${f.creditLimit.toLocaleString()}, Balance: KSh ${f.currentCreditBalance.toLocaleString()})`);
  }

  // 5. Seed 50 Agrovet Products with Batches & Branch Stocks
  console.log(`\n5. Seeding ${PRODUCTS.length} Agrovet Products with FEFO Batches...`);
  const now = new Date();
  let added = 0;
  let skipped = 0;

  for (const p of PRODUCTS) {
    if (itemsOnly && await prisma.product.findUnique({ where: { sku: p.sku }, select: { id: true } })) {
      skipped++;
      console.log(`   Skipped existing item: ${p.sku}`);
      continue;
    }
    const categoryId = categoryMap[p.category];
    if (!categoryId) {
      console.error(`Missing category: ${p.category}`);
      continue;
    }

    const { category, monthsExpiry, quantity, ...data } = p;

    await prisma.$transaction(async (prisma) => {
      const product = await prisma.product.upsert({
        where: { sku: p.sku },
        update: {
          ...data,
          categoryId,
          quantityInStock: quantity,
          totalCost: (p.costPrice || 0) * quantity,
        },
        create: {
          ...data,
          categoryId,
          quantityInStock: quantity,
          totalCost: (p.costPrice || 0) * quantity,
        },
      });

      // Allocate to branch
      await prisma.productBranchStock.upsert({
        where: { productId_branchId: { productId: product.id, branchId: branch.id } },
        update: { quantityInStock: quantity, initialAllocation: quantity },
        create: {
          productId: product.id,
          branchId: branch.id,
          quantityInStock: quantity,
          initialAllocation: quantity,
        },
      });

      // Create FEFO batch
      let expiryDate = null;
      if (monthsExpiry) {
        expiryDate = new Date();
        expiryDate.setMonth(expiryDate.getMonth() + monthsExpiry);
      }

      const batchNumber = `${p.sku.split("-").slice(0, 3).join("-")}-B26`;
      const existingBatch = await prisma.productBatch.findFirst({
        where: { productId: product.id, branchId: branch.id, batchNumber },
      });

      if (!existingBatch) {
        await prisma.productBatch.create({
          data: {
            productId: product.id,
            branchId: branch.id,
            batchNumber,
            expiryDate,
            quantity,
            costPrice: p.costPrice,
            receivedAt: now,
          },
        });
      } else {
        await prisma.productBatch.update({
          where: { id: existingBatch.id },
          data: { quantity, expiryDate, costPrice: p.costPrice },
        });
      }

    });
    added++;
    console.log(`   ✓ [${p.sku}] ${p.name} — KSh ${p.sellingPrice.toLocaleString()} (Stock: ${quantity})`);
  }

  // Update business name setting to reflect Agrovet
  if (!itemsOnly) await prisma.setting.upsert({
    where: { key: "business_name" },
    update: { value: "NebTech Agrovet Supplies" },
    create: { key: "business_name", value: "NebTech Agrovet Supplies", description: "Business name shown on receipts" },
  });

  console.log("\n========================================================");
  console.log("🌾 Agrovet Seed Finished Successfully!");
  if (itemsOnly) {
    console.log(`   - ${added} products added, ${skipped} existing products preserved`);
    console.log(`   - Target branch: ${branch.name} (${branch.code})`);
    return;
  }
  console.log(`   - 6 Categories created/updated`);
  console.log(`   - 8 Major agrovet suppliers registered`);
  console.log(`   - 5 Farmer customers (with credit profiles) added`);
  console.log(`   - ${PRODUCTS.length} Authentic Agrovet products seeded with FEFO batches`);
  console.log("========================================================\n");
}

main()
  .catch((e) => {
    console.error("Seed error:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
